program tests

  ! Driver program for FRUIT unit tests in:
  ! src/day02a_test.f90

  ! Generated by FRUITPy.

  use fruit
  use day02a_test

  implicit none
  integer :: failed_count

  call init_fruit

  call run_test_case(test_scan_strategy_example,"test_scan_strategy_example")
  call run_test_case(test_scan_strategy_input,"test_scan_strategy_input")

  call get_failed_count(failed_count)
  call fruit_summary
  call fruit_finalize
  if (failed_count > 0) stop 1

end program tests