name: Code quality

on: [push]

jobs:

  runall:
    runs-on: ubuntu-latest
    steps:
    - name: Install GFortran
      run: |
        apt-get update && \
        apt-get upgrade && \
        apt-get install --yes --no-install-recommends make gfortran && \
        rm -rf /var/lib/apt/lists/* 
    - name: Install FRUITpy
      run: |
        python -m pip install --upgrade FRUITPy pip pkg_resources setuptools
    - uses: actions/checkout@v3
    - name: Make and run all binaries
      run: |
        make runall
